### ISSUE TITLE
Api changes proposal

### ISSUE THREAD

**Issue by re2005** [bitdust-io/devel#456]
Can we make a few changes on the APIs ?

**First is the base url.**

Normally the API's don't end with the version, that's added somewhere else.

ie: http://localhost:8180/network/connected/v1

Could be:
http://localhost:8180/v1/network/connected/ OR just ignore the V1 in this case, we will always have a single version from the API running.
That prevents all calls on my console to be named as `V1`

API's that return more data than FE needs

**Identity**
http://localhost:8180/identity/get/v1

<img width="478" alt="console" src="https://user-images.githubusercontent.com/2920357/71258854-72895e00-2337-11ea-9e8a-62a5cd8605cc.png">

```
{
   "execution":"0.000507",
   "result":[
      {
         "certificates":[

         ],
         "contacts":[
            "tcp://185.204.2.109:7509"
         ],
         "date":"Nov 29, 2019",
         "global_id":"superino@bahamas.ai",
         "idurl":"http://bahamas.ai/superino.xml",
         "name":"superino",
         "postage":"1",
         "publickey":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmy0eZLAo96hpkwhRC6JSwWyLSXQupyZSYXRTFdPyVRIcK0nq2NBd9GRntFyQR1m+lB9sLBiHPbFBQn998P1rB1ap01mBsMXMMWiJKn43+GdpbzecMVDyJ9x+SZM26MZ2mVTmA2ecgptVou5j9nWE3HRNnxKIRkGBROd5zHDpqgrw4fwzQggahFlL6rhuxz4eVEpJcJopJhIgZXQmUaTX0wqwRBTM8JE0FxTmStO4onlrsDrhL/087ob2zwcVqT5AdETd6An0Ki8C5dugjLSoCsl+bdsRftDLaZGbeFr2zJgK6jek31XiKSpkMP5Klr1WRixJzMzfUY16gWdjzW9rb",
         "revision":"56",
         "scrubbers":[

         ],
         "signature":"15529136975192915975090490694465860781666510512166473388349953888928209847522328771631013712735806173653385652731291786880884868291182843674684841176510496478546148131119570142277039204038566786131850032040734150099447790693533362005445898510163379497081049655002531638067276416752049536214217715759707761724647164969590741281021810086373814713020825063262932041429750739645834581987848141592190975941718676391372912904116194027966219374453384957354205288624382896636959776725160366814820252442303739612470948613338619437141187528453591879190778494541972005806728969486356282049706451192343765991077741715214234488742",
         "sources":[
            "http://bahamas.ai/superino.xml",
            "http://bitrex.ai/superino.xml",
            "http://p2p-id.ru/superino.xml",
            "http://p2p-alice.ai/superino.xml",
            "http://bitdust.ai/superino.xml"
         ],
         "version":"sources Darwin-18.7.0-x86_64-i386-64bit"
      }
   ],
   "status":"OK"
}
```

Why results is an array if I always get ONE single identity ?
I only need a few keys here:

**name, userId, globalId.** and lets please use CamelCase for the response ?

About **Websockets** ?

The most usage would be for:
- Events
- Messages
-User
- Friends
- Files
- Keys

That's all for now.
Cheers

**Comment by vesellov** [comment]
Thanks for your proposal @re2005  !   about the first request - it is very possible.
this PR suppose to provide you that: https://github.com/bitdust-io/devel/pull/458

**Comment by vesellov** [comment]
but i do not think it will help you a lot....  instead of `v1, v1, v1, v1, ... `  you will see now  `list, list, get, list, get` ... :)

**Comment by vesellov** [comment]
about the API response structure: I thought to make it consistent across all methods... some methods returns only fixed dict structure, some methods returns list of items - could be of different types, some suppose to return dictionary with different items... 
So my idea was to always return a list and items in the list can be of different types so you can always understand what it is just by iterating over the `result` list.   and it is more flexible to my opinion if we want to change some methods in the future.  is it a big problem for you @re2005 ?

**Comment by vesellov** [comment]
why CamelCase is better?  it is a Python giving you data, not Java, right ? :)))

**Comment by vesellov** [comment]
closing because no response for a while. some of those proposals already implemented
