### ISSUE TITLE
return proper HTTP response codes from REST API

### ISSUE THREAD

**Issue by vesellov** [bitdust-io/devel#505]

**Comment by vesellov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [update engine documentation](https://trello.com/c/meHlQ79p/444-update-engine-documentation)

**Comment by Sukkoto** [comment]
Hi, @vesellov. I'd like to get into REST API docs. I'm totally new to documentation and Github. I'm in the middle of learning about these things, so any contributions I would make would be incredibly slow, but I'd do my best. 

I don't even know how to find your current docs. Where are they so I can look at them?

**Comment by vesellov** [comment]
Hi @Sukkoto ! Welcome to the project! nice to meet you!

unfortunately i didn't had time to prepare good API docs for BitDust. Currently I have that page which is automatically generated from the source code of file `interface/api.py` : https://bitdust.io/wiki/api

This is all we have at the moment, which is almost nothing :)))

The REST API logic in the engine is concentrated in the file https://github.com/bitdust-io/devel/blob/master/interface/api_rest_http_server.py

This is a Twisted TCP server that serves HTTP requests to `localhost:8180` and executes methods from `interface/api.py` file. 

You can find those methods in api.py file: `api.OK()`, `api.RESULT()`

**Comment by vesellov** [comment]
To make it more simple for us to cooperate we can have a chat via Telegram ( https://t.me/bitdust ) or Slack ( https://bitdust-dev.slack.com - I will send you an invite ) if you like.

**Comment by Sukkoto** [comment]
Sure! I'm Slack. I just started using it, though, so let me know if there is anything you need from me to send me an invite.

**Comment by vesellov** [comment]
can you pls drop a email to bitdust.io@gmail.com so i can add you @Sukkoto 👍

**Comment by vesellov** [comment]
This suppose to be fixed already in the latest version.
