### ISSUE TITLE
auto check/fix code with linter

### ISSUE THREAD

**Issue by vesellov** [bitdust-io/devel#506]

**Comment by codingcosmonaut** [comment]
Hi, I have used pylint with tox to check the code on possible errors and warning. Does that sound like a solution for this issue?

**Comment by vesellov** [comment]
super! would be great, @codingcosmonaut  :+1: 

you can implement that inside Makefile as well .  Really appreciate your initiative !

**Comment by daaavo** [comment]
Hello is this issue still open? If that's the case I'd like to take this issue.
My solution is to implement pre-commit and within the yaml file add all the linters to check the possible errors and warning in the code before it's commited. Also with the help of a .toml file manage the config of each linter to avoid conflicts

**Comment by vesellov** [comment]
Hi @daaavo !
Yes, please go ahead. This feature is still very desired... I just never had enough time to focus on the code quality, so you are very welcome here.

**Comment by daaavo** [comment]
Thanks I'll start as soon as the Hacktoberfest begin, could you add the label of hacktoberfest to the issue, or do you think that with the labels that are already is enough for my participation to count?

**Comment by KevinArellano94** [comment]
Oh yeah HacktOberFest!!!  Should've save the other changes for it as well u.u

**Comment by vesellov** [comment]
Cool, never heard about Hacktoberfest before. :+1: 
Also updated repository topics and added #hacktoberfest

**Comment by vesellov** [comment]
Looks great, @daaavo :+1: 
Respect!
