### ISSUE TITLE
prepare CONTRIBUTION.md

### ISSUE THREAD

**Issue by vesellov** [bitdust-io/devel#507]

**Comment by Flodur871** [comment]
Is this still relevant?

**Comment by vesellov** [comment]
Hi @Flodur871 .

Yes, I think so. I didn't have time to start that document, but I really believe some introduction and help for people willing to contrubute BitDust project must have.

If you have any ideas and would like to help there - please just give a try.  I will help you further. ;)

**Comment by Flodur871** [comment]
I began working on a document and now just happened to see that you already have [one](https://github.com/bitdust-io/devel/blob/master/CONTRIBUTING.md) :)

**Comment by vesellov** [comment]
Ah. Indeed, @Flodur871.
The page does exist, albeit with very basic information.
Then I will close that ticket.
But you are always welcome to contribute / update / fix things on that page or any other parts of the project. :+1:
