### ISSUE TITLE
implement messages history paggination

### ISSUE THREAD

**Issue by vesellov** [bitdust-io/devel#511]

**Comment by vesellov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [group chat messaging](https://trello.com/c/xKye7g3R/443-group-chat-messaging)

**Comment by dubesar** [comment]
Can you explain exactly what is needed?

**Comment by vesellov** [comment]
Hi @dubesar ! welcome to the project! I can explain, sure.
Sorry, do not have time to describe every story, so it is very good that you asked directly 👍 

In the `message_db.py` https://github.com/bitdust-io/devel/blob/master/chat/message_database.py#L95 we store all chat conversations in `sqlite3` database.

When you receive a message from another user BitDust decrypt the body of the message and populate it to the UI so message can be displayed in the APP right away. Also message is stored in the local sqlite3 DB as a single record, see `insert()` method here: https://github.com/bitdust-io/devel/blob/master/chat/message_database.py#L170

User also need to be able to switch between different chat conversations - that means we need to display in UI already received messages. UI suppose to call to `/v1/message/history` API method here : https://github.com/bitdust-io/devel/blob/master/interface/api_rest_http_server.py#L982

Currently that call suppose to return all messages at once... but it can be very long conversation, right? So UI and the Python engine require some basic pagination methods.

My idea was to just add two extra parameters to that method like `pagesize` and `offset` that can be used to fetch messages page by page when user scrolls the chat window up and down... 

If you take a look at `api.py` file where all API logic is concentrated you can find `message_history(user, offset=0, limit=100)` method I already implemented. So this story is pretty much about to just populate the parameters and test how it works via API calls. 

To make it more simple we can have a chat via Telegram ( https://t.me/bitdust ) or Slack ( bitdust-dev.slack.com - I will send you an invite ) if you like.

**Comment by dubesar** [comment]
@vesellov I understood the problem to some extent!! Have to spend some time on the codebase to get familiarity. Please if you can possibly add me to the slack channel!!

**Comment by vesellov** [comment]
Sure, but i need your email. Can you send a message to bitdust.io@gmail.com ?

**Comment by vesellov** [comment]
implemented
