### ISSUE TITLE
Websockets events on linux doesn't send "stream_message"

### ISSUE THREAD

**Issue by re2005** [bitdust-io/devel#546]
ON linux seems that only one type of events are coming.

type = event.

```

{
  payload: { data: {}, event_id: 'my-list-files-refreshed' },
  type: 'event'
}
{
  payload: { data: {}, event_id: 'my-backup-index-synchronized' },
  type: 'event'
}
{
  payload: { data: {}, event_id: 'my-keys-out-of-sync' },
  type: 'event'
}
{
  payload: { data: {}, event_id: 'my-storage-not-ready-yet' },
  type: 'event'
}
{
  payload: {
    data: {
      error: 'not possible to restore some keys, backup copies unreliable'
    },
    event_id: 'my-keys-synchronize-failed'
  },
  type: 'event'
}
{
  payload: { data: {}, event_id: 'my-backup-index-synchronized' },
  type: 'event'
}
{
  payload: { data: {}, event_id: 'my-keys-out-of-sync' },
  type: 'event'
}
{
  payload: { data: {}, event_id: 'my-storage-not-ready-yet' },
  type: 'event'
}
{
  payload: {
    data: {
      error: 'not possible to restore some keys, backup copies unreliable'
    },
    event_id: 'my-keys-synchronize-failed'
  },
  type: 'event'
}
```

**Comment by vesellov** [comment]
it seems there are some errors as i see from those events. we currently have `event`, `stream_message` and `api_call` types in the websocket output stream...   i do not believe Mac and Linux have some difference here.

can you try to call some API via websocket (not sure if it is possible for you to connect on that linux box via remote port 8280  )  @re2005 ?   

each api call should make `api_call` type event  populated in the ws stream.

the events of `stream_message` type are populated by `service_message_history()` service which was not probably started. that is why you basically see only type `event`
