### ISSUE TITLE
https://bitdust.io/#roadmap

### ISSUE THREAD

**Issue by KevinArellano94** [bitdust-io/devel#689]
Not sure if a typo or I'm not understanding it well.  On the main site there are 4 Quarter icon, where it starts with Q4 => Q1 => Q1 => Q3.  Could be a different interpretation on my part.  Let  me know if so i can PR it and update it for you.

https://bitdust.io/#roadmap

**Comment by KevinArellano94** [comment]
Closing this issue since I created it inside wrong repo XD

**Comment by vesellov** [comment]
Indeed, thank you for reaching out here, @KevinArellano94 !
